/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WriteRouteImport } from './routes/write'
import { Route as AdminCoinsRouteImport } from './routes/admin.coins'
import { Route as AdminNovelsRouteImport } from './routes/admin.novels'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AuthorDashboardRouteImport } from './routes/author.dashboard'
import { Route as AuthorNovelsRouteImport } from './routes/author.novels'
import { Route as AuthorsIdRouteImport } from './routes/authors.$id'
import { Route as NovelsIdRouteImport } from './routes/novels.$id'
import { Route as WalletTransactionsRouteImport } from './routes/wallet.transactions'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as AuthorNovelsIdRouteImport } from './routes/author.novels.$id'
import { Route as AuthorNovelsNewRouteImport } from './routes/author.novels.new'
import { Route as NovelsIdChapterChapterIdRouteImport } from './routes/novels.$id.chapter.$chapterId'
import { Route as AuthorNovelsIdChapterChapterIdRouteImport } from './routes/author.novels.$id.chapter.$chapterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoinsRoute = AdminCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNovelsRoute = AdminNovelsRouteImport.update({
  id: '/novels',
  path: '/novels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AuthorDashboardRoute = AuthorDashboardRouteImport.update({
  id: '/author/dashboard',
  path: '/author/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorNovelsRoute = AuthorNovelsRouteImport.update({
  id: '/author/novels',
  path: '/author/novels',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIdRoute = AuthorsIdRouteImport.update({
  id: '/authors/$id',
  path: '/authors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsIdRoute = NovelsIdRouteImport.update({
  id: '/novels/$id',
  path: '/novels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletTransactionsRoute = WalletTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => WalletRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorNovelsIdRoute = AuthorNovelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthorNovelsRoute,
} as any)
const AuthorNovelsNewRoute = AuthorNovelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthorNovelsRoute,
} as any)
const NovelsIdChapterChapterIdRoute =
  NovelsIdChapterChapterIdRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => NovelsIdRoute,
  } as any)
const AuthorNovelsIdChapterChapterIdRoute =
  AuthorNovelsIdChapterChapterIdRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => AuthorNovelsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/write': typeof WriteRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/novels': typeof AdminNovelsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/author/dashboard': typeof AuthorDashboardRoute
  '/author/novels': typeof AuthorNovelsRouteWithChildren
  '/authors/$id': typeof AuthorsIdRoute
  '/novels/$id': typeof NovelsIdRouteWithChildren
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/author/novels/$id': typeof AuthorNovelsIdRouteWithChildren
  '/author/novels/new': typeof AuthorNovelsNewRoute
  '/novels/$id/chapter/$chapterId': typeof NovelsIdChapterChapterIdRoute
  '/author/novels/$id/chapter/$chapterId': typeof AuthorNovelsIdChapterChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/write': typeof WriteRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/novels': typeof AdminNovelsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/author/dashboard': typeof AuthorDashboardRoute
  '/author/novels': typeof AuthorNovelsRouteWithChildren
  '/authors/$id': typeof AuthorsIdRoute
  '/novels/$id': typeof NovelsIdRouteWithChildren
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/author/novels/$id': typeof AuthorNovelsIdRouteWithChildren
  '/author/novels/new': typeof AuthorNovelsNewRoute
  '/novels/$id/chapter/$chapterId': typeof NovelsIdChapterChapterIdRoute
  '/author/novels/$id/chapter/$chapterId': typeof AuthorNovelsIdChapterChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/write': typeof WriteRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/novels': typeof AdminNovelsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/author/dashboard': typeof AuthorDashboardRoute
  '/author/novels': typeof AuthorNovelsRouteWithChildren
  '/authors/$id': typeof AuthorsIdRoute
  '/novels/$id': typeof NovelsIdRouteWithChildren
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/author/novels/$id': typeof AuthorNovelsIdRouteWithChildren
  '/author/novels/new': typeof AuthorNovelsNewRoute
  '/novels/$id/chapter/$chapterId': typeof NovelsIdChapterChapterIdRoute
  '/author/novels/$id/chapter/$chapterId': typeof AuthorNovelsIdChapterChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/discover'
    | '/library'
    | '/login'
    | '/profile'
    | '/rankings'
    | '/register'
    | '/settings'
    | '/wallet'
    | '/write'
    | '/admin/coins'
    | '/admin/novels'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/author/dashboard'
    | '/author/novels'
    | '/authors/$id'
    | '/novels/$id'
    | '/wallet/transactions'
    | '/api/auth/$'
    | '/api/payments/webhook'
    | '/author/novels/$id'
    | '/author/novels/new'
    | '/novels/$id/chapter/$chapterId'
    | '/author/novels/$id/chapter/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/discover'
    | '/library'
    | '/login'
    | '/profile'
    | '/rankings'
    | '/register'
    | '/settings'
    | '/wallet'
    | '/write'
    | '/admin/coins'
    | '/admin/novels'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/author/dashboard'
    | '/author/novels'
    | '/authors/$id'
    | '/novels/$id'
    | '/wallet/transactions'
    | '/api/auth/$'
    | '/api/payments/webhook'
    | '/author/novels/$id'
    | '/author/novels/new'
    | '/novels/$id/chapter/$chapterId'
    | '/author/novels/$id/chapter/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/discover'
    | '/library'
    | '/login'
    | '/profile'
    | '/rankings'
    | '/register'
    | '/settings'
    | '/wallet'
    | '/write'
    | '/admin/coins'
    | '/admin/novels'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/author/dashboard'
    | '/author/novels'
    | '/authors/$id'
    | '/novels/$id'
    | '/wallet/transactions'
    | '/api/auth/$'
    | '/api/payments/webhook'
    | '/author/novels/$id'
    | '/author/novels/new'
    | '/novels/$id/chapter/$chapterId'
    | '/author/novels/$id/chapter/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RankingsRoute: typeof RankingsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  WalletRoute: typeof WalletRouteWithChildren
  WriteRoute: typeof WriteRoute
  AuthorDashboardRoute: typeof AuthorDashboardRoute
  AuthorNovelsRoute: typeof AuthorNovelsRouteWithChildren
  AuthorsIdRoute: typeof AuthorsIdRoute
  NovelsIdRoute: typeof NovelsIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coins': {
      id: '/admin/coins'
      path: '/coins'
      fullPath: '/admin/coins'
      preLoaderRoute: typeof AdminCoinsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/novels': {
      id: '/admin/novels'
      path: '/novels'
      fullPath: '/admin/novels'
      preLoaderRoute: typeof AdminNovelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/author/dashboard': {
      id: '/author/dashboard'
      path: '/author/dashboard'
      fullPath: '/author/dashboard'
      preLoaderRoute: typeof AuthorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/novels': {
      id: '/author/novels'
      path: '/author/novels'
      fullPath: '/author/novels'
      preLoaderRoute: typeof AuthorNovelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$id': {
      id: '/authors/$id'
      path: '/authors/$id'
      fullPath: '/authors/$id'
      preLoaderRoute: typeof AuthorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/$id': {
      id: '/novels/$id'
      path: '/novels/$id'
      fullPath: '/novels/$id'
      preLoaderRoute: typeof NovelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/transactions': {
      id: '/wallet/transactions'
      path: '/transactions'
      fullPath: '/wallet/transactions'
      preLoaderRoute: typeof WalletTransactionsRouteImport
      parentRoute: typeof WalletRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/novels/$id': {
      id: '/author/novels/$id'
      path: '/$id'
      fullPath: '/author/novels/$id'
      preLoaderRoute: typeof AuthorNovelsIdRouteImport
      parentRoute: typeof AuthorNovelsRoute
    }
    '/author/novels/new': {
      id: '/author/novels/new'
      path: '/new'
      fullPath: '/author/novels/new'
      preLoaderRoute: typeof AuthorNovelsNewRouteImport
      parentRoute: typeof AuthorNovelsRoute
    }
    '/novels/$id/chapter/$chapterId': {
      id: '/novels/$id/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/novels/$id/chapter/$chapterId'
      preLoaderRoute: typeof NovelsIdChapterChapterIdRouteImport
      parentRoute: typeof NovelsIdRoute
    }
    '/author/novels/$id/chapter/$chapterId': {
      id: '/author/novels/$id/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/author/novels/$id/chapter/$chapterId'
      preLoaderRoute: typeof AuthorNovelsIdChapterChapterIdRouteImport
      parentRoute: typeof AuthorNovelsIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCoinsRoute: typeof AdminCoinsRoute
  AdminNovelsRoute: typeof AdminNovelsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoinsRoute: AdminCoinsRoute,
  AdminNovelsRoute: AdminNovelsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WalletRouteChildren {
  WalletTransactionsRoute: typeof WalletTransactionsRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletTransactionsRoute: WalletTransactionsRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

interface AuthorNovelsIdRouteChildren {
  AuthorNovelsIdChapterChapterIdRoute: typeof AuthorNovelsIdChapterChapterIdRoute
}

const AuthorNovelsIdRouteChildren: AuthorNovelsIdRouteChildren = {
  AuthorNovelsIdChapterChapterIdRoute: AuthorNovelsIdChapterChapterIdRoute,
}

const AuthorNovelsIdRouteWithChildren = AuthorNovelsIdRoute._addFileChildren(
  AuthorNovelsIdRouteChildren,
)

interface AuthorNovelsRouteChildren {
  AuthorNovelsIdRoute: typeof AuthorNovelsIdRouteWithChildren
  AuthorNovelsNewRoute: typeof AuthorNovelsNewRoute
}

const AuthorNovelsRouteChildren: AuthorNovelsRouteChildren = {
  AuthorNovelsIdRoute: AuthorNovelsIdRouteWithChildren,
  AuthorNovelsNewRoute: AuthorNovelsNewRoute,
}

const AuthorNovelsRouteWithChildren = AuthorNovelsRoute._addFileChildren(
  AuthorNovelsRouteChildren,
)

interface NovelsIdRouteChildren {
  NovelsIdChapterChapterIdRoute: typeof NovelsIdChapterChapterIdRoute
}

const NovelsIdRouteChildren: NovelsIdRouteChildren = {
  NovelsIdChapterChapterIdRoute: NovelsIdChapterChapterIdRoute,
}

const NovelsIdRouteWithChildren = NovelsIdRoute._addFileChildren(
  NovelsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RankingsRoute: RankingsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  WalletRoute: WalletRouteWithChildren,
  WriteRoute: WriteRoute,
  AuthorDashboardRoute: AuthorDashboardRoute,
  AuthorNovelsRoute: AuthorNovelsRouteWithChildren,
  AuthorsIdRoute: AuthorsIdRoute,
  NovelsIdRoute: NovelsIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
